local o = vim.opt

o.relativenumber = true
o.number = true
o.tabstop = 2
o.shiftwidth = 2
o.expandtab = true
o.smarttab = true
o.autoindent = true
o.wrap = false
o.ignorecase = true
o.smartcase = true
o.cursorline = true
o.termguicolors = true
o.background = "dark"
o.signcolumn = "yes"
o.backspace = "indent,eol,start"
o.splitright = true
o.splitbelow = true
o.cmdheight = 0
o.showmode = false
o.conceallevel = 0
